version: '3'
 
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
 
    env_file:
      - ./.env
    depends_on:
      - db
 
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: 'dev'
      POSTGRES_PASSWORD: 'dev'
      POSTGRES_DB: 'crypto-analysis'
    volumes: 
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A backend_django worker --loglevel=INFO
    volumes:
      - ./:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - app

volumes:
  pgdata:
