# Generated by Django 4.1.1 on 2022-09-13 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_payments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='user',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
