# Generated by Django 4.1.1 on 2022-09-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_payments', '0003_remove_paymentmodel_user_paymentmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
