# Generated by Django 4.1 on 2022-09-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.DateTimeField()),
                ('open', models.FloatField()),
            ],
            options={
                'db_table': 'graph',
            },
        ),
    ]
