# Generated by Django 4.1.1 on 2023-01-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cripto_info', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraphModel',
        ),
    ]
