# Generated by Django 4.1.1 on 2023-01-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cripto_info', '0002_delete_graphmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingviewBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('what', models.CharField(max_length=50)),
                ('interval', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'tradingview_bot',
            },
        ),
    ]
