# Generated by Django 4.1.1 on 2023-01-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cripto_info', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('bot', models.CharField(max_length=50, null=True)),
                ('price', models.FloatField()),
                ('what', models.CharField(max_length=50)),
                ('interval', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'bots',
            },
        ),
        migrations.DeleteModel(
            name='TradingviewBot',
        ),
    ]
